# Generated by Django 2.0.6 on 2018-06-25 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0002_auto_20180625_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='location_folder',
            field=models.FilePathField(allow_folders=True, default='~'),
        ),
    ]
