# Generated by Django 2.0.6 on 2018-06-26 20:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookmarks', '0004_auto_20180626_1700'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalBookmark',
            fields=[
                ('bookmark_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bookmarks.Bookmark')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('bookmarks.bookmark',),
        ),
        migrations.RenameField(
            model_name='bookmark',
            old_name='created_at',
            new_name='date_added',
        ),
        migrations.RemoveField(
            model_name='bookmark',
            name='last_modified',
        ),
        migrations.RemoveField(
            model_name='bookmark',
            name='location_folder',
        ),
        migrations.AddField(
            model_name='bookmark',
            name='bookmark_type',
            field=models.CharField(choices=[('url', 'folder')], default='url', max_length=6),
        ),
    ]
