# Generated by Django 2.0.6 on 2018-06-26 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0005_auto_20180626_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='bookmark_type',
            field=models.CharField(choices=[('u', 'url'), ('f', 'folder')], default='u', max_length=6),
        ),
    ]
